/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package map;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import javax.swing.JComponent;

/**
 *
 * @author Sur Tad
 */
public class MapInterface extends javax.swing.JFrame {

    Map mp;
    int count=0;
    /**
     * Creates new form MapInterface
     */
    public MapInterface() {
        initComponents();
        setGlassPane(new MyGlas());
        getGlassPane().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
void setMap(Map m){
   mp=m;
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showPath_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        bole_label = new javax.swing.JLabel();
        cmc_label = new javax.swing.JLabel();
        gerji_label = new javax.swing.JLabel();
        hayahulet_label = new javax.swing.JLabel();
        megenagna_label = new javax.swing.JLabel();
        aratKilo_label = new javax.swing.JLabel();
        kazanchis_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pathcost_label = new javax.swing.JLabel();
        value_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uniform Cost Search");
        setBackground(new java.awt.Color(241, 234, 234));
        setResizable(false);

        showPath_button.setBackground(new java.awt.Color(241, 234, 234));
        showPath_button.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        showPath_button.setForeground(new java.awt.Color(65, 35, 18));
        showPath_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(65, 35, 18), 1, true));
        showPath_button.setLabel("Show Path");
        showPath_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPath_buttonActionPerformed(evt);
            }
        });

        reset_button.setBackground(new java.awt.Color(241, 234, 234));
        reset_button.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        reset_button.setForeground(new java.awt.Color(65, 35, 18));
        reset_button.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(65, 35, 18), 1, true));
        reset_button.setLabel("Reset");
        reset_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_buttonMouseClicked(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(65, 35, 18));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(241, 234, 234));
        jTextField1.setText("First select a starting location, then the destination and click on  “Show Path”");

        jTextField4.setBackground(new java.awt.Color(65, 35, 18));
        jTextField4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(241, 234, 234));
        jTextField4.setText("    City Map");
        jTextField4.setToolTipText("");

        bole_label.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        bole_label.setForeground(new java.awt.Color(251, 176, 59));
        bole_label.setText("  Bole");
        bole_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 35, 18)));
        bole_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bole_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bole_labelMouseClicked(evt);
            }
        });

        cmc_label.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        cmc_label.setForeground(new java.awt.Color(251, 176, 59));
        cmc_label.setText("  CMC");
        cmc_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 35, 18)));
        cmc_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmc_label.setOpaque(true);
        cmc_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmc_labelMouseClicked(evt);
            }
        });

        gerji_label.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        gerji_label.setForeground(new java.awt.Color(251, 176, 59));
        gerji_label.setText("  Gerji");
        gerji_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 35, 18)));
        gerji_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gerji_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerji_labelMouseClicked(evt);
            }
        });

        hayahulet_label.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        hayahulet_label.setForeground(new java.awt.Color(251, 176, 59));
        hayahulet_label.setText("  Hayahulet");
        hayahulet_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 35, 18)));
        hayahulet_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hayahulet_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hayahulet_labelMouseClicked(evt);
            }
        });

        megenagna_label.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        megenagna_label.setForeground(new java.awt.Color(251, 176, 59));
        megenagna_label.setText("  Megenagna");
        megenagna_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 35, 18)));
        megenagna_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        megenagna_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                megenagna_labelMouseClicked(evt);
            }
        });

        aratKilo_label.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        aratKilo_label.setForeground(new java.awt.Color(251, 176, 59));
        aratKilo_label.setText("  AratKilo");
        aratKilo_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 35, 18)));
        aratKilo_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aratKilo_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aratKilo_labelMouseClicked(evt);
            }
        });

        kazanchis_label.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        kazanchis_label.setForeground(new java.awt.Color(251, 176, 59));
        kazanchis_label.setText("  Kazanchis");
        kazanchis_label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 35, 18)));
        kazanchis_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kazanchis_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kazanchis_labelMouseClicked(evt);
            }
        });

        jLabel1.setText("360");

        jLabel2.setText("260");

        jLabel3.setText("260");

        jLabel4.setText("125");

        jLabel5.setText("125");

        jLabel6.setText("260");

        jLabel7.setText("260");

        jLabel8.setText("125");

        jLabel9.setText("125");

        pathcost_label.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        pathcost_label.setForeground(new java.awt.Color(65, 35, 18));
        pathcost_label.setText("Path cost:");

        value_label.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel5)
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(kazanchis_label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(118, 118, 118)
                                .addComponent(hayahulet_label, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(aratKilo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(488, 488, 488)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(megenagna_label, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(130, 130, 130)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(gerji_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel8))
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel2)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bole_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(showPath_button, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pathcost_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(value_label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(cmc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(megenagna_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(bole_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gerji_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(aratKilo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hayahulet_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(kazanchis_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(148, 148, 148))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(196, 196, 196))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(164, 164, 164))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(pathcost_label)
                                            .addComponent(value_label))
                                        .addGap(41, 41, 41)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(showPath_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void drawPath(){
    mp.temp=mp.destination;
    while(mp.temp!=null){
            if("CMC".equals(mp.nameOf(mp.temp)))
                cmc_label.setForeground(Color.RED);
            if("Gerji".equals(mp.nameOf(mp.temp)))
                gerji_label.setForeground(Color.RED);
            if("Bole".equals(mp.nameOf(mp.temp)))
                bole_label.setForeground(Color.RED);
            if("Hayahulet".equals(mp.nameOf(mp.temp)))
                hayahulet_label.setForeground(Color.RED);
            if("Kazanchis".equals(mp.nameOf(mp.temp)))
                kazanchis_label.setForeground(Color.RED);
            if("AratKilo".equals(mp.nameOf(mp.temp)))
                aratKilo_label.setForeground(Color.RED);
            if("Megenagna".equals(mp.nameOf(mp.temp)))
                megenagna_label.setForeground(Color.RED);
            
            mp.temp=mp.sourceLocation(mp.temp);
        }
}

   
public class MyGlas extends JComponent {

    public void paint(Graphics g) {

        Rectangle cBounds = cmc_label.getBounds();
        Rectangle bBounds = bole_label.getBounds();
        Rectangle gBounds = gerji_label.getBounds();
        Rectangle hBounds = hayahulet_label.getBounds();
        Rectangle kBounds = kazanchis_label.getBounds();
        Rectangle mBounds = megenagna_label.getBounds();
        Rectangle aBounds = aratKilo_label.getBounds();

        g.drawLine(cBounds.x+48, cBounds.y+27, bBounds.x, bBounds.y);
        g.drawLine(gBounds.x+48, gBounds.y+13, bBounds.x, bBounds.y+13);
        g.drawLine(hBounds.x+81, hBounds.y, bBounds.x, bBounds.y+27);
        g.drawLine(kBounds.x+79, kBounds.y+13, hBounds.x, hBounds.y+13);
        g.drawLine(aBounds.x+68, aBounds.y+13, kBounds.x, kBounds.y);
        g.drawLine(aBounds.x+34, aBounds.y, mBounds.x, mBounds.y+27);
        g.drawLine(mBounds.x+86, mBounds.y+13, gBounds.x, gBounds.y+13);
        g.drawLine(mBounds.x+86, mBounds.y+27, hBounds.x, hBounds.y);
        g.drawLine(mBounds.x+43, mBounds.y+27, kBounds.x+39, kBounds.y);
        
    }
}


    
    private void showPath_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPath_buttonActionPerformed
        // TODO add your handling code here:
        mp.uniformCostSearch();
        drawPath();
        value_label.setText(Integer.toString(mp.pathCost(mp.destination)));
    }//GEN-LAST:event_showPath_buttonActionPerformed

    private void cmc_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmc_labelMouseClicked
        // TODO add your handling code here:
    if(count<2){
        cmc_label.setForeground(Color.GREEN);
    if(mp.starting == null){
        mp.starting=mp.CMC; count++;}
    else
    {mp.destination=mp.CMC;count++; showPath_button.enable(true);}
    }
    }//GEN-LAST:event_cmc_labelMouseClicked

    private void gerji_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerji_labelMouseClicked
        // TODO add your handling code here:
        if(count<2){
        gerji_label.setForeground(Color.GREEN);
    if(mp.starting == null)
    {mp.starting=mp.Gerji; count++; }
    else
    {mp.destination=mp.Gerji; count++;showPath_button.enable();}
    }
    }//GEN-LAST:event_gerji_labelMouseClicked

    private void bole_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bole_labelMouseClicked
        // TODO add your handling code here:
        if(count<2){
        bole_label.setForeground(Color.GREEN);
    if(mp.starting == null)
    {mp.starting=mp.Bole; count++; }
    else
    {mp.destination=mp.Bole; count++;showPath_button.enable();}
    }
    }//GEN-LAST:event_bole_labelMouseClicked

    private void hayahulet_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hayahulet_labelMouseClicked
        // TODO add your handling code here:
        if(count<2){
        hayahulet_label.setForeground(Color.GREEN);
    if(mp.starting == null)
    {mp.starting=mp.Hayahulet; count++;}
    else
    {mp.destination=mp.Hayahulet; count++;showPath_button.enable();}
    }
    }//GEN-LAST:event_hayahulet_labelMouseClicked

    private void kazanchis_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kazanchis_labelMouseClicked
        // TODO add your handling code here:
                if(count<2){
        kazanchis_label.setForeground(Color.GREEN);
    if(mp.starting == null)
    {mp.starting=mp.Kazanchis; count++; }
    else
    {mp.destination=mp.Kazanchis; count++; showPath_button.enable();}
    }
    }//GEN-LAST:event_kazanchis_labelMouseClicked

    private void aratKilo_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aratKilo_labelMouseClicked
        // TODO add your handling code here:
      if(count<2){
        aratKilo_label.setForeground(Color.GREEN);
    if(mp.starting == null)
    {mp.starting=mp.AratKilo; count++; }
    else
    {mp.destination=mp.AratKilo; count++; showPath_button.enable();}
    }
    }//GEN-LAST:event_aratKilo_labelMouseClicked

    private void megenagna_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_megenagna_labelMouseClicked
        // TODO add your handling code here:
                if(count<2){
        megenagna_label.setForeground(Color.GREEN);
    if(mp.starting == null)
             {mp.starting=mp.Megenagna; count++; }
    else
            {mp.destination=mp.Megenagna; count++; showPath_button.enable();}
    }
    }//GEN-LAST:event_megenagna_labelMouseClicked

    private void reset_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_buttonMouseClicked
        // TODO add your handling code here:
         cmc_label.setForeground(Color.ORANGE);
         gerji_label.setForeground(Color.ORANGE);
         bole_label.setForeground(Color.ORANGE);
         hayahulet_label.setForeground(Color.ORANGE);
         kazanchis_label.setForeground(Color.ORANGE);
         aratKilo_label.setForeground(Color.ORANGE);
         megenagna_label.setForeground(Color.ORANGE);
         count=0;
         mp.resetLocation(mp.AratKilo);mp.resetLocation(mp.Bole);
         mp.resetLocation(mp.CMC);mp.resetLocation(mp.Gerji);
         mp.resetLocation(mp.Kazanchis);mp.resetLocation(mp.Hayahulet);
         mp.resetLocation(mp.Megenagna);
         mp.starting=null; mp.destination=null;
         value_label.setText("");
    }//GEN-LAST:event_reset_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapInterface().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aratKilo_label;
    private javax.swing.JLabel bole_label;
    private javax.swing.JLabel cmc_label;
    private javax.swing.JLabel gerji_label;
    private javax.swing.JLabel hayahulet_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel kazanchis_label;
    private javax.swing.JLabel megenagna_label;
    private javax.swing.JLabel pathcost_label;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton showPath_button;
    private javax.swing.JLabel value_label;
    // End of variables declaration//GEN-END:variables
}
